// Generated by CoffeeScript 1.3.3
(function() {
  var Calculator, NumberFormat;

  NumberFormat = (function() {

    function NumberFormat() {}

    NumberFormat.format = function(number, decimals, dec_point, thousands_sep) {
      var decimal, decimalPoint, negative;
      if (decimals == null) {
        decimals = 0;
      }
      if (dec_point == null) {
        dec_point = ',';
      }
      if (thousands_sep == null) {
        thousands_sep = ' ';
      }
      negative = number < 0 ? '-' : '';
      number = Math.abs(number);
      decimal = ((number - parseInt(number)).toFixed(decimals)).slice(2);
      number = ("" + (parseInt(number.toFixed(decimals)))).split('').reverse().join('').replace(/...(?!$)/g, "$&" + (thousands_sep.replace(/\$/g, '$$$$'))).split('').reverse().join('');
      decimalPoint = decimals !== 0 ? dec_point : '';
      return "" + negative + number + decimalPoint + decimal;
    };

    return NumberFormat;

  })();

  Calculator = (function() {

    function Calculator() {
      this.make_select_issue_value();
      this.make_select_pay_period();
    }

    Calculator.prototype.make_select_issue_value = function() {
      var select_issue_value, value, _i, _results;
      select_issue_value = $("select[name='issue-value']");
      _results = [];
      for (value = _i = 1000; _i <= 50000; value = _i += 1000) {
        _results.push(select_issue_value.append($("<option value=" + value + ">" + (NumberFormat.format(value)) + " Kč</option>")));
      }
      return _results;
    };

    Calculator.prototype.make_select_pay_period = function() {
      var select_pay_period, value, _i, _len, _ref, _results;
      select_pay_period = $("select[name='pay-period']");
      _ref = ['45 týdnů', '60 týdnů'];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        value = _ref[_i];
        _results.push(select_pay_period.append($("<option value=" + value + ">" + value + "</option>")));
      }
      return _results;
    };

    return Calculator;

  })();

  jQuery(function() {
    return new Calculator();
  });

}).call(this);
